### ISSUE TITLE
NHentai System

### ISSUE THREAD

**Issue by itchono** [itchono/comrade-next#4]
# Goals
- Port over the NHentai viewer system from [Ground Dragon](https://github.com/itchono/Comrade/blob/master/src/Gomrade/nsfw.go)

# Requirements for Feature Parity
- [x] View any available six digit work
- [x] Search for tags
- [x] Multiple-proxy system (using other providers, Google Translate proxy) for Cloudflare bypass

# New Ideas to Explore
- Caching downloaded works
- Performance Improvements
- Modularity
- - Panel viewer, using https://github.com/njean42/kumiko
And https://github.com/reidenong/ComicPanelSegmentation
- [x] #15
- [x] #16

# Implementation Plan
* Make a new NHentai library under `lib`, which abstracts away the scraping operations from the commands, similarly to `booru_lib`
* Make the commands interface under `modules`, and make it similar to what Ground Dragon uses
